import "./globals.css";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="corporate">
      <body className={inter.className} suppressHydrationWarning={true}>
        <div className="navbar bg-base-100">
          <a className="normal-case text-xl" href="/">
            <Image src="/BPS.png" alt="Logo BPS" width={100} height={100} />{" "}
            BUTIK BPS 1571
          </a>
        </div>
        {children}
      </body>
    </html>
  );
}
